# ansible/roles/jenkins/tasks/configure_jenkins.yml
- name: Configure Jenkins home
  lineinfile:
    path: /etc/default/jenkins
    regexp: '^JENKINS_HOME='
    line: 'JENKINS_HOME={{ jenkins_home }}'
    create: yes

- name: Set Jenkins directory ownership
  file:
    path: "{{ jenkins_home }}"
    owner: jenkins
    group: jenkins
    recurse: yes

- name: Add Jenkins user to Docker group
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Restart Jenkins service
  systemd:
    name: jenkins
    state: restarted
    daemon_reload: yes

- name: Check Jenkins service status  # 添加此调试任务
  command: systemctl status jenkins
  register: jenkins_status
  changed_when: false

- name: Display Jenkins service status  # 添加此调试任务
  debug:
    var: jenkins_status.stdout_lines

- name: Check Jenkins logs  # 添加此调试任务
  command: journalctl -u jenkins --no-pager -n 50
  register: jenkins_logs
  changed_when: false

- name: Display Jenkins logs  # 添加此调试任务
  debug:
    var: jenkins_logs.stdout_lines

- name: Wait for Jenkins to start up
  uri:
    url: "http://localhost:8080/login"
    status_code: 200
    validate_certs: no
  register: jenkins_service_status
  until: jenkins_service_status.status == 200
  retries: 30
  delay: 5

- name: Wait for initialAdminPassword file
  wait_for:
    path: "{{ jenkins_home }}/secrets/initialAdminPassword"
    state: present
    timeout: 120  # 增加超时时间到 2 分钟