---
- name: Configure Jenkins home
  lineinfile:
    path: /etc/default/jenkins
    regexp: '^JENKINS_HOME='
    line: 'JENKINS_HOME={{ jenkins_home }}'
    create: yes

- name: Set Jenkins directory ownership
  file:
    path: "{{ jenkins_home }}"
    owner: jenkins
    group: jenkins
    recurse: yes

- name: Add Jenkins user to Docker group
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Start and enable Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes

- name: Wait for Jenkins to start up
  uri:
    url: "http://localhost:8080/login"
    status_code: 200
    validate_certs: no
  register: jenkins_service_status
  until: jenkins_service_status.status == 200
  retries: 30
  delay: 5