---
- name: Stop Jenkins service
  systemd:
    name: jenkins
    state: stopped

- name: Configure Jenkins home in systemd override directory
  file:
    path: /etc/systemd/system/jenkins.service.d
    state: directory
    mode: '0755'

- name: Create systemd override file
  copy:
    dest: /etc/systemd/system/jenkins.service.d/override.conf
    content: |
      [Service]
      Environment="JENKINS_HOME=/data/jenkins"

- name: Configure Jenkins home in defaults file
  lineinfile:
    path: /etc/default/jenkins
    regexp: '^JENKINS_HOME='
    line: 'JENKINS_HOME=/data/jenkins'
    create: yes

- name: Create init.groovy.d directory
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    mode: '0755'
    owner: jenkins
    group: jenkins

- name: Copy pipeline creation script
  template:
    src: create-pipeline.groovy.j2
    dest: "{{ jenkins_home }}/init.groovy.d/create-pipeline.groovy"
    owner: jenkins
    group: jenkins
    mode: '0644'
  notify: restart jenkins

- name: Copy security initialization script
  template:
    src: basic-security.groovy.j2
    dest: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
    owner: jenkins
    group: jenkins
    mode: '0644'

- name: Set Jenkins directory ownership
  file:
    path: "{{ jenkins_home }}"
    owner: jenkins
    group: jenkins
    recurse: yes

- name: Add Jenkins user to Docker group
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Reload systemd configurations
  systemd:
    daemon_reload: yes

- name: Start and enable Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes

- name: Wait for Jenkins to start up
  uri:
    url: "http://localhost:8080/login"
    status_code: 200
    validate_certs: no
  register: jenkins_service_status
  until: jenkins_service_status.status == 200
  retries: 1
  delay: 5

- name: Wait for initialAdminPassword file
  wait_for:
    path: "{{ jenkins_home }}/secrets/initialAdminPassword"
    state: present
    timeout: 120

- name: Get Jenkins initial admin password
  slurp:
    src: "{{ jenkins_home }}/secrets/initialAdminPassword"
  register: jenkins_admin_password
  when: jenkins_service_status is success

- name: Create JCasC directory
  file:
    path: "{{ jenkins_home }}/casc_configs"
    state: directory
    owner: jenkins
    group: jenkins
    mode: "0755"

- name: Set Jenkins environment variables
  lineinfile:
    path: /etc/default/jenkins
    line: "{{ item }}"
    create: yes
  with_items:
    - 'JENKINS_HOME="{{ jenkins_home }}"'
    - 'JENKINS_ADMIN_USER="{{ jenkins_admin_username }}"'
    - 'JENKINS_ADMIN_PASSWORD="{{ jenkins_admin_password }}"'
    - 'CASC_JENKINS_CONFIG="{{ jenkins_home }}/casc_configs"'
    - 'JAVA_OPTS="-Djenkins.install.runSetupWizard=false -Dcasc.jenkins.config={{ jenkins_home }}/casc_configs ${JAVA_OPTS}"'
  notify: restart jenkins