---
- name: Wait for Jenkins to be fully operational
  uri:
    url: "{{ jenkins_url }}/login"
    method: GET
    status_code: [200, 403]
    validate_certs: no
    follow_redirects: yes
  register: jenkins_check
  until: jenkins_check.status in [200, 403]
  retries: 60
  delay: 5

- name: Install Jenkins plugins
  jenkins_plugin:
    name: "{{ item }}"
    url: "{{ jenkins_url }}"
    url_username: "{{ jenkins_admin_username }}"
    url_password: "{{ jenkins_admin_password }}"
    timeout: 120
    validate_certs: no
  with_items: "{{ jenkins_plugins }}"
  notify: 
    - restart jenkins
    - wait for jenkins
  register: plugin_result
  until: plugin_result is success
  retries: 3
  delay: 5