---
- name: Wait for Jenkins to be fully operational
  uri:
    url: "{{ jenkins_url }}/login"
    method: GET
    status_code: [200, 403]
    validate_certs: no
    follow_redirects: yes
  register: jenkins_check
  until: jenkins_check.status in [200, 403]
  retries: 60
  delay: 5

- name: Ensure plugins directory exists
  file:
    path: "{{ jenkins_home }}/plugins"
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: Download plugin files
  get_url:
    url: "https://updates.jenkins.io/latest/{{ item }}.hpi"
    dest: "{{ jenkins_home }}/plugins/{{ item }}.hpi"
    owner: jenkins
    group: jenkins
    mode: '0644'
    validate_certs: no
  with_items: "{{ jenkins_plugins }}"
  register: plugin_download
  notify: restart jenkins

- name: Set plugins permissions
  file:
    path: "{{ jenkins_home }}/plugins"
    owner: jenkins
    group: jenkins
    mode: '0755'
    recurse: yes
  when: plugin_download.changed
  notify: restart jenkins