---
- name: Download Jenkins CLI
  get_url:
    url: "http://localhost:8080/jnlpJars/jenkins-cli.jar"
    dest: "/tmp/jenkins-cli.jar"
    mode: '0440'

- name: Install Jenkins plugins
  command: >
    java -jar /tmp/jenkins-cli.jar -s http://localhost:8080/ 
    -auth {{ jenkins_admin_username }}:{{ jenkins_admin_password.content | b64decode }}
    install-plugin {{ item }} -deploy
  with_items: "{{ jenkins_plugins }}"
  register: plugin_installation
  changed_when: "'Installing' in plugin_installation.stdout"
  notify: restart jenkins

- name: Display Jenkins initial admin password
  debug:
    msg: "Jenkins initial admin password: {{ jenkins_admin_password.content | b64decode }}"
  when: jenkins_admin_password is defined