---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: yes

- name: Install common dependencies
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - git
    state: present

- name: Install Java 17
  apt:
    name: openjdk-17-jre
    state: present