---
- name: Get Jenkins plugin manager
  get_url:
    url: "https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.12.11/jenkins-plugin-manager-2.12.11.jar"
    dest: "{{ jenkins_home }}/jenkins-plugin-manager.jar"
    owner: jenkins
    group: jenkins
    mode: "0755"
  register: plugin_manager_download
  until: "'OK' in plugin_manager_download.msg or '304' in plugin_manager_download.msg or 'file already exists' in plugin_manager_download.msg"
  retries: 5
  delay: 10
  check_mode: false

- name: Copy plugins.txt to Jenkins
  copy:
    src: "plugins.txt"
    dest: "/tmp/plugins.txt"
    owner: jenkins
    group: jenkins
    mode: "0644"

- name: Check if Jenkins plugins folder exists
  stat:
    path: "{{ jenkins_home }}/plugins"
  register: jenkins_plugins_folder

- name: Create Jenkins plugins folder if not exists
  file:
    path: "{{ jenkins_home }}/plugins"
    state: directory
    owner: jenkins
    group: jenkins
    mode: "0755"
  when: not jenkins_plugins_folder.stat.exists

- name: Install Jenkins plugins
  command:
    cmd: >
      java -jar jenkins-plugin-manager.jar
      --war /usr/share/java/jenkins.war
      --plugin-download-directory ./plugins
      --plugin-file /tmp/plugins.txt
      --latest-specified
      --verbose
  args:
    chdir: "{{ jenkins_home }}"
  register: plugin_installation
  retries: 3
  delay: 10
  until: plugin_installation.rc == 0
  changed_when: plugin_installation.rc == 0
  notify: restart jenkins

- name: Set plugins directory permissions
  file:
    path: "{{ jenkins_home }}/plugins"
    owner: jenkins
    group: jenkins
    mode: "0755"
    recurse: yes
  when: plugin_installation.changed
