---
- import_tasks: install_dependencies.yml
- import_tasks: configure_storage.yml
- import_tasks: install_jenkins.yml
- import_tasks: install_docker.yml
- import_tasks: configure_jenkins.yml
- import_tasks: install_plugins.yml

- name: Wait for Jenkins to start up
  uri:
    url: "{{ jenkins_url }}/login"
    status_code: 200
    validate_certs: no
  register: jenkins_service_status
  until: jenkins_service_status.status == 200
  retries: 1
  delay: 5
  changed_when: false