---
- import_tasks: install_dependencies.yml
- import_tasks: configure_storage.yml
- import_tasks: install_jenkins.yml
- import_tasks: install_docker.yml
- import_tasks: configure_jenkins.yml
- import_tasks: install_plugins.yml