pipeline {
    agent any

    stages {
        stage ('Prepare') {
            steps {
                script {
                    echo 'Preparing...'
                }
            }
        }
        stage ('Build') {
            steps {
                script {
                    echo 'Building...'
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }
        stage ('Deploy') {
            steps {
                script {
                    echo 'Deploying...'
                    // withAws
                }
            }
        }
    }
}