- name: restart jenkins
  systemd:
    name: jenkins
    state: restarted
    daemon_reload: yes
  notify: verify jenkins start

- name: verify jenkins start
  wait_for:
    port: 8080
    delay: 10
    timeout: 30
  notify: wait for jenkins

- name: wait for jenkins
  uri:
    url: "{{ jenkins_url }}/login"
    method: GET
    status_code: [200, 403]
    follow_redirects: true
    validate_certs: no
    timeout: 30
  register: result
  until: result.status in [200, 403]
  retries: 6
  delay: 10
  notify: get jenkins logs

- name: get jenkins logs
  shell: "journalctl -u jenkins -n 50 --no-pager"
  register: jenkins_logs
  when: result.failed is defined
  notify: get crumb

- name: get crumb
  uri:
    url: "{{ jenkins_url }}/crumbIssuer/api/json"
    method: GET
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: yes
    status_code: [200, 403]
    validate_certs: no
  register: crumb_result
  until: crumb_result.status in [200, 403]
  retries: 6
  delay: 10
  when: result.status in [200, 403]
  notify: reload jenkins configuration

- name: reload jenkins configuration
  uri:
    url: "{{ jenkins_url }}/reload"
    method: POST
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: yes
    headers:
      "{{ crumb_result.json.crumbRequestField }}": "{{ crumb_result.json.crumb }}"
    status_code: [200, 302]
    validate_certs: no
  register: reload_result
  when: crumb_result.json is defined
  retries: 5
  delay: 15
  until: reload_result.status in [200, 302]

- name: verify nodejs installation
  uri:
    url: "{{ jenkins_url }}/manage/configureTools/"
    method: GET
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: yes
    validate_certs: no
    return_content: yes
  register: nodejs_verify
  until: "'Node20' in nodejs_verify.content"
  retries: 6
  delay: 10
  when: reload_result.status in [200, 302]