---
- name: restart jenkins
  systemd:
    name: jenkins
    state: restarted
    daemon_reload: yes

- name: wait for jenkins
  uri:
    url: "{{ jenkins_url }}/login"
    method: GET
    status_code: [200, 403]
    validate_certs: no
    follow_redirects: yes
  register: result
  until: result.status in [200, 403]
  retries: 60
  delay: 5