- name: restart jenkins
  systemd:
    name: jenkins
    state: restarted
    daemon_reload: yes
  notify: wait for jenkins

- name: wait for jenkins
  uri:
    url: "http://{{ ansible_host }}:{{ jenkins_http_port }}/login"
    method: GET
    status_code: [200, 403]
    validate_certs: no
    follow_redirects: true  # 使用 true 而不是 yes
    timeout: 60  # 增加超时时间
  register: result
  until: result.status in [200, 403]
  retries: 3  # 增加重试次数
  delay: 10   # 增加延迟时间

# 添加检查步骤
- name: check jenkins process
  shell: "ps aux | grep jenkins"
  register: jenkins_process
  when: result.failed is defined and result.failed

- name: show jenkins status
  shell: "systemctl status jenkins"
  register: jenkins_status
  when: jenkins_process is defined

- name: get crumb for reload
  uri:
    url: "http://{{ ansible_host }}:{{ jenkins_http_port }}/crumbIssuer/api/json"
    method: GET
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: yes
    status_code: [200, 403]
    validate_certs: no
  register: crumb_result
  until: crumb_result.status in [200, 403]
  retries: 12
  delay: 10
  when: result.status in [200, 403]

- name: reload jenkins configuration
  shell: |
    curl -X POST \
    -u {{ jenkins_admin_username }}:{{ jenkins_admin_password }} \
    -H "{{ crumb_result.json.crumbRequestField }}:{{ crumb_result.json.crumb }}" \
    http://{{ ansible_host }}:{{ jenkins_http_port }}/reload
  args:
    warn: false
  register: reload_result
  when: crumb_result.json is defined
  retries: 5
  delay: 15
  until: reload_result.rc == 0
  ignore_errors: true