---
- name: restart jenkins
  systemd:
    name: jenkins
    state: restarted
    daemon_reload: yes

- name: wait for jenkins
  uri:
    url: "http://{{ ansible_host }}:{{ jenkins_http_port }}/login"
    method: GET
    status_code: [200, 403]
    validate_certs: no
    follow_redirects: yes
  register: result
  until: result.status in [200, 403]
  retries: 60
  delay: 5

- name: reload jenkins configuration
  uri:
    url: "http://{{ ansible_host }}:{{ jenkins_http_port }}/reload"
    method: POST
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: yes
    validate_certs: no
  ignore_errors: true