- name: restart jenkins
  systemd:
    name: jenkins
    state: restarted
    daemon_reload: yes
  notify: verify jenkins start

- name: verify jenkins start
  wait_for:
    port: 8080
    delay: 10
    timeout: 30
  notify: wait for jenkins

- name: wait for jenkins
  uri:
    url: "http://localhost:8080/login"
    method: GET
    status_code: [200, 403]
    follow_redirects: true
    validate_certs: no
    timeout: 30
  register: result
  until: result.status in [200, 403]
  retries: 6
  delay: 10
  notify: get jenkins logs

- name: get jenkins logs
  shell: "journalctl -u jenkins -n 50 --no-pager"
  register: jenkins_logs
  when: result.failed is defined
  notify: get crumb

- name: get crumb
  uri:
    url: "http://localhost:8080/crumbIssuer/api/json"
    method: GET
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: yes
    status_code: [200, 403]
    validate_certs: no
  register: crumb_result
  until: crumb_result.status in [200, 403]
  retries: 6
  delay: 10
  when: result.status in [200, 403]
  notify: reload jenkins configuration

- name: reload jenkins configuration
  shell: |
    curl -X POST \
    -u {{ jenkins_admin_username }}:{{ jenkins_admin_password }} \
    -H "{{ crumb_result.json.crumbRequestField }}:{{ crumb_result.json.crumb }}" \
    http://localhost:8080/reload
  args:
    warn: false
  register: reload_result
  when: crumb_result.json is defined
  retries: 5
  delay: 15
  until: reload_result.rc == 0
  ignore_errors: true