name: PR Discord Notification

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        if: github.event.pull_request.draft == false
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            ${{ github.event.action == 'opened' && '🆕 New PR:' || '🔄 PR Updated:' }} ${{ github.event.pull_request.html_url }}
            **Title:** ${{ github.event.pull_request.title }}
            **Author:** ${{ github.event.pull_request.user.login }}

      - name: Discord merge notification
        if: github.event.pull_request.merged == true && github.event.pull_request.draft == false
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            🎉 PR Merged: ${{ github.event.pull_request.html_url }}
            **Title:** ${{ github.event.pull_request.title }}
            **Merged by:** ${{ github.event.pull_request.merged_by.login }}
