name: Enhanced Discord Notifications

on:
  pull_request:
    types: [opened, reopened, closed, ready_for_review, synchronize]
  push:
    branches: [main, develop]
    tags: ['v*']
  workflow_dispatch:

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  DISCORD_THREAD_ID: 1332133384075481098
  SKIP_KEYWORD: '[skip notification]'

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    concurrency:
      group: notify-${{ github.event_name }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Prepare PR Metadata
        id: prepare
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const { data: pr } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number
              });
              return {
                changed_files: pr.changed_files,
                additions: pr.additions,
                deletions: pr.deletions,
                labels: pr.labels.map(label => label.name).join(', ') || 'None',
                branch: pr.head.ref,
                base: pr.base.ref
              };
            } catch (error) {
              core.setFailed(`Failed to get PR data: ${error.message}`);
              return {};
            }

      - name: PR Notification
        if: |
          github.event_name == 'pull_request' &&
          !contains(github.event.pull_request.title, env.SKIP_KEYWORD) &&
          !github.event.pull_request.draft
        uses: Ilshidur/action-discord@master
        with:
          args: |
            {
              "embeds": [{
                "title": "${{ github.event.pull_request.merged && '🚀 Merged PR' || '🔄 Updated PR' }}",
                "color": ${{ github.event.pull_request.merged && '32768' || '5814783' }},
                "fields": [
                  {
                    "name": "Title",
                    "value": "[${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})",
                    "inline": false
                  },
                  {
                    "name": "Branch",
                    "value": "`${{ fromJSON(steps.prepare.outputs.result).branch }} ➜ ${{ fromJSON(steps.prepare.outputs.result).base }}`",
                    "inline": true
                  },
                  {
                    "name": "Changes",
                    "value": "📄 ${{ fromJSON(steps.prepare.outputs.result).changed_files }} files (+${{ fromJSON(steps.prepare.outputs.result).additions }}/-${{ fromJSON(steps.prepare.outputs.result).deletions }})",
                    "inline": true
                  },
                  {
                    "name": "Labels",
                    "value": "${{ fromJSON(steps.prepare.outputs.result).labels }}",
                    "inline": true
                  }
                ],
                "footer": {
                  "text": "By ${{ github.actor }} • ${{ github.event.pull_request.updated_at }}"
                }
              }],
              "thread_id": "${{ toJSON(env.DISCORD_THREAD_ID) }}"
            }
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Push Notification
        if: |
          github.event_name == 'push' &&
          !contains(github.event.head_commit.message, env.SKIP_KEYWORD)
        uses: Ilshidur/action-discord@master
        with:
          args: |
            {
              "embeds": [{
                "title": "📦 ${{ contains(github.ref, 'main') && 'Production' || 'Development' }} Update",
                "color": ${{ contains(github.ref, 'main') && '16711680' || '32768' }},
                "fields": [
                  {
                    "name": "Branch",
                    "value": "`${{ github.ref_name }}`",
                    "inline": true
                  },
                  {
                    "name": "Commits",
                    "value": "${{ github.event.commits.length }}",
                    "inline": true
                  }
                ],
                "description": "```\n${{ github.event.head_commit.message }}\n```",
                "footer": {
                  "text": "By ${{ github.actor }} • ${{ github.event.head_commit.timestamp }}"
                }
              }],
              "thread_id": "${{ toJSON(env.DISCORD_THREAD_ID) }}"
            }
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Error Notification
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: '⚠️ Discord notification failed. Check Actions logs for details.'
              });
            } catch (error) {
              console.error('Failed to create error comment:', error);
            }
