name: Frontend CD - UAT Deployment

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Frontend CI - Build & Test"]
    types:
      - completed
    branches: [uat]

permissions:
  id-token: write
  contents: read

jobs:
  deploy-to-uat:
    uses: ./.github/workflows/frontend-deploy.yml
    with:
      environment: UAT
      bucket_name: uat-foundation-innovatefuture-uat-frontend-static
      cloudfront_id: E3JTL07A6BPHK
      website_url: https://uat.innovatefuture.foundation
      api_url: https://uat.innovatefuture.foundation
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_UAT_ACCOUNT }}
      DISCORD_WEBHOOK: ${{ secrets.DEV_PR_DISCORD_WEBHOOK }}
