name: Test Workflow

on:
  workflow_dispatch:  # 允许手动触发
  push:              # 推送时自动触发
    branches:
      - 'feature/**' # 只在 feature 分支上触发

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Step 1
        run: |
          echo "This is a test workflow"
          echo "Current branch: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"

      - name: Test Step 2
        run: |
          echo "Environment variables:"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB_SHA: $GITHUB_SHA"
          ls -la 